#!/bin/bash
set -e

# Add setup for API
echo "Setup for API lab..."
echo "Static App: $STATIC_APP"
echo "Dynamic App: $DYNAMIC_APP"

php /var/apache2/templates/config-template.php > /etc/apache2/sites-available/001-reverse-proxy.conf

# Apache gets grumpy about PID files pre-existing
rm -rf /var/run/apache2/apache2.pid

exec apache2ctl -DFOREGROUND
